### ISSUE TITLE
Pls share the IMU dataset file to test 

### ISSUE THREAD

**Issue by jaehyek** [yolish/har-with-imu-transformer#1]
Thanks for sharing the project 'Inertial-based Activity Recognition with Transformers'. 
If you share the IMU dataset file to google driver, it would be helpful to understand more

**Comment by LukasHackl2** [comment]
I would need it too.

**Comment by JAaron9311** [comment]
Same here. I would appreciate it if you can share the dataset to run the code.

**Comment by yolish** [comment]
Hi, thank you for your interest in our repository! The datasets are public so we cannot share them directly. I will add links for download.

**Comment by nchappa** [comment]
@yolish Can you please add the links to download the datasets? I appreciate your patience! Thanks in advance!

**Comment by gituser-hb** [comment]
Same for me, I want to get the dataset download link. Thanks!

**Comment by yolish** [comment]
Unfortunately, we cannot directly share the data since it is not our to share (IP) but you can contact the authors of these datasets directly and ask for them (the links for these datasets are no longer available; please see references in our Datasets section if you'd like to contact the authors). I If you have other datasets, you can use them as well as the training is very simple and fast to execute. You can see the expected format in the IMUDataset class (util/IMUDataset.py) and I can also give instructions if you run into any issues.
